In this notebook, I collect the business/first class passenger ratio on a given origin-destination pair (on a single flight) for a given quarter from the DB1B Coupon data collected for 2016 and 2017 for the origin and destination airports of interest.

In [1]:
import pickle
import pandas as pd
import numpy as np

Read in the saved DB1B Coupon data

In [2]:
with open('db1b_coup.pkl', 'rb') as file1:
    db1b_coup = pickle.load(file1)

In [3]:
db1b_coup.head()

,ItinID,MktID,Year,Quarter,Origin,Dest,RPCarrier,Passengers,FareClass
11,201611982005,20161198200503,2016,1,JFK,PIT,DL,1.0,X
35,201612118321,20161211832103,2016,1,JFK,SYR,DL,1.0,X
67,201612399761,20161239976103,2016,1,JFK,BUF,G7,1.0,X
70,201612430914,20161243091403,2016,1,LGA,ROC,G7,1.0,X
75,201613105237,20161310523703,2016,1,LGA,BOS,UA,1.0,G

Compute number of business passengers (Coded in `FareClass` as C or D) and all passengers for a given Year, Quarter and O-D pair 4-tuple. Then get the ratio of business passengers to all passengers and save the file.

In [4]:
bus_pass = db1b_coup[db1b_coup['FareClass'].isin(['C', 'D'])].groupby(['Year', 'Quarter', 'Origin', 'Dest']).sum()[['Passengers']]

In [5]:
all_pass = db1b_coup.groupby(['Year', 'Quarter', 'Origin', 'Dest']).sum()[['Passengers']]

In [6]:
bus_pass_ratio = (bus_pass/all_pass).fillna(0).reset_index()
bus_pass_ratio.rename({'Passengers': 'BusPassRatio'}, axis = 1, inplace=True)

In [7]:
bus_pass_ratio

      Year  Quarter Origin Dest  BusPassRatio
0     2016        1    EWR  ATL      0.000438
1     2016        1    EWR  AUS      0.000000
2     2016        1    EWR  BNA      0.000000
3     2016        1    EWR  BOS      0.000229
4     2016        1    EWR  BTV      0.000000
5     2016        1    EWR  BUF      0.000000
6     2016        1    EWR  CHS      0.000000
7     2016        1    EWR  CLE      0.000000
8     2016        1    EWR  CLT      0.000734
9     2016        1    EWR  CMH      0.000000
10    2016        1    EWR  CVG      0.000000
11    2016        1    EWR  DAL      0.000000
12    2016        1    EWR  DCA      0.000000
13    2016        1    EWR  DEN      0.000000
14    2016        1    EWR  DFW      0.001669
15    2016        1    EWR  DTW      0.000422
16    2016        1    EWR  FLL      0.000000
17    2016        1    EWR  GRR      0.000000
18    2016        1    EWR  GSO      0.000000
19    2016        1    EWR  GSP      0.000000
20    2016        1    EWR  HOU      0.000000
21    2016        1    EWR  IAD      0.000000
22    2016        1    EWR  IAH      0.000000
23    2016        1    EWR  IND      0.000000
24    2016        1    EWR  JAX      0.000000
25    2016        1    EWR  LAS      0.000000
26    2016        1    EWR  LAX      0.000000
27    2016        1    EWR  MCO      0.000000
28    2016        1    EWR  MDW      0.000000
29    2016        1    EWR  MEM      0.000000
...    ...      ...    ...  ...           ...
1449  2018        1    LGA  LAS      0.000000
1450  2018        1    LGA  LAX      0.010638
1451  2018        1    LGA  MCO      0.002852
1452  2018        1    LGA  MDW      0.000000
1453  2018        1    LGA  MEM      0.027199
1454  2018        1    LGA  MIA      0.048058
1455  2018        1    LGA  MKE      0.000000
1456  2018        1    LGA  MSP      0.008441
1457  2018        1    LGA  MSY      0.000000
1458  2018        1    LGA  MYR      0.000000
1459  2018        1    LGA  ORD      0.025661
1460  2018        1    LGA  ORF      0.000000
1461  2018        1    LGA  PBI      0.007100
1462  2018        1    LGA  PDX      0.000000
1463  2018        1    LGA  PHL      0.016479
1464  2018        1    LGA  PHX      0.070175
1465  2018        1    LGA  PIT      0.014165
1466  2018        1    LGA  PWM      0.000000
1467  2018        1    LGA  RDU      0.008900
1468  2018        1    LGA  RIC      0.000513
1469  2018        1    LGA  ROC      0.000000
1470  2018        1    LGA  RSW      0.000000
1471  2018        1    LGA  SAN      0.000000
1472  2018        1    LGA  SAV      0.000000
1473  2018        1    LGA  SDF      0.000000
1474  2018        1    LGA  SFO      0.000000
1475  2018        1    LGA  SNA      0.000000
1476  2018        1    LGA  STL      0.012684
1477  2018        1    LGA  SYR      0.000000
1478  2018        1    LGA  TPA      0.000000

[1479 rows x 5 columns]

In [8]:
with open('bus_pass_ratio.pkl', 'wb') as file1:
    pickle.dump(bus_pass_ratio, file1)